name: rocket-data-ingestion

services:
  producer_one:
    build:
      context: .
      dockerfile: docker/dockerfile.producer.1
    ports:
      - "8044:8044"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://producer_one:8044/ping"]
      interval: 10s
      timeout: 10s
      retries: 3
